package com.cnh.dao;

import com.cnh.pojo.MmallPayInfo;

public interface MmallPayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int insert(MmallPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int insertSelective(MmallPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    MmallPayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int updateByPrimaryKeySelective(MmallPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int updateByPrimaryKey(MmallPayInfo record);
}