package com.cnh.dao;

import com.cnh.pojo.MmallCategory;

public interface MmallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int insert(MmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int insertSelective(MmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    MmallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int updateByPrimaryKeySelective(MmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int updateByPrimaryKey(MmallCategory record);
}