package com.cnh.dao;

import com.cnh.pojo.MmallUser;

public interface MmallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int insert(MmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int insertSelective(MmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    MmallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int updateByPrimaryKeySelective(MmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Tue Sep 24 09:23:14 CST 2019
     */
    int updateByPrimaryKey(MmallUser record);
}